name: My Workflows secrets

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Access PRIVATE_KEY
        env:
          APOD_API_KEY: ${{ secrets.PRIVATE_KEY }}
        run: echo PRIVATE_KEY=\"$PRIVATE_KEY\" > ./local.properties
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build the app
        run: ./gradlew assembleDebug
     


      
