name: My Workflows secrets

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access PRIVATE_KEY
        env:
          APOD_API_KEY: ${{ secrets.PRIVATE_KEY }}
        run: echo PRIVATE_KEY=\"$PRIVATE_KEY\" > ./local.properties
      - name: Build the app
        run: ./gradlew assembleDebug
      - name: Make gradlew executable
        run: chmod +x ./gradlew


      
